### ISSUE TITLE
How to use this library to draw chart

### ISSUE THREAD

**Issue by vivekratansinha** [kunjara/jyotish-draw#4]
I am struggling to draw a chart using the data generated by jyotish library. A simple example would be highly appreciated.

**Comment by krishnaguragain** [comment]
It's addon package for https://github.com/kunjara/jyotish
Please use https://github.com/kunjara/jyotish for calculation and chart generation.

**Comment by vivekratansinha** [comment]
@krishnaguragain thank you for your message. I have successfully generated the chart using https://github.com/kunjara/jyotish
I wish to use that output to draw the chart using this library.
A simple PHP example to achieve this would be helpful.

**Comment by krishnaguragain** [comment]
@vivekratansinha Currently I don't have any example for it, but you can get through this example https://github.com/kunjara/jyotish/issues/1#issuecomment-388033948. Phpstorm will help you by showing autosuggest.

**Comment by HSBSINGH** [comment]
@vivekratansinha can you give example how you solved to draw chart using this library. It would be highly appreciated.
Thanks

**Comment by vivekratansinha** [comment]
> 
> 
> @vivekratansinha can you give example how you solved to draw chart using this library. It would be highly appreciated.
> Thanks

@HSBSINGH As per my last message, I only managed to use the https://github.com/kunjara/jyotish, NOT https://github.com/kunjara/jyotish-draw

**Comment by HSBSINGH** [comment]
@kunjara 
@vivekratansinha 

Its required some options parameters, but options are optional as per class not cleared what to pass ...... do you had any idea?

Fatal error: Uncaught Jyotish\Base\Exception\InvalidArgumentException: Options must be an array. in D:\Projects\xampp\htdocs\Astrology\jyotish\vendor\kunjara\jyotish\src\Base\Traits\OptionTrait.php:38 Stack trace: #0 D:\Projects\xampp\htdocs\Astrology\jyotish\vendor\kunjara\jyotish\src\Draw\Plot\Chakra\Renderer.php(127): Jyotish\Draw\Renderer\AbstractRenderer->setOptions('') #1 D:\Projects\xampp\htdocs\Astrology\jyotish\vendor\kunjara\jyotish\src\Draw\Plot\Chakra\Renderer.php(82): Jyotish\Draw\Plot\Chakra\Renderer->drawRashiLabel() #2 D:\Projects\xampp\htdocs\Astrology\jyotish\vendor\kunjara\jyotish\src\Draw\Draw.php(98): Jyotish\Draw\Plot\Chakra\Renderer->drawChakra(Object(Jyotish\Base\Data), 0, 0, NULL) #3 D:\Projects\xampp\htdocs\Astrology\jyotish\index.php(95): Jyotish\Draw\Draw->drawChakra(Object(Jyotish\Base\Data), 0, 0) #4 {main} thrown in D:\Projects\xampp\htdocs\Astrology\jyotish\vendor\kunjara\jyotish\src\Base\Traits\OptionTrait.php on line 38

**Comment by ultratronic** [comment]
please help I couldnt plot the chakra chart .:( @kunjara @
